POST http://localhost:8081/api/v1/
Content-Type: application/json

{
  "email":"al@gmail.com",
  "password": "Test12345-"
}

###
GET http://localhost:8083/api/v1/createuser
###
POST http://localhost:8083/api/v1/newSession
Content-Type: application/json

{
  "id": "55ffe178-c544-4a17-9b7b-6f87cff9754c",
  "firstname": "ale",
  "lastname": "laneri",
  "email": "bla@gmail",
  "password": "test12345",
  "username": "magno"
}

###

GET http://localhost:8081/api/v1/users
###
GET http://localhost:8083/api/v1/diceValue

###
GET http://localhost:8083/api/v1/searchSession

###

GET http://localhost:8083/api/v1/session/000c0efd-2322-4435-b66b-b67c258379e0

###
POST http://localhost:8083/api/v1/searchSession2
Content-Type: application/json

{
  "id": null,
  "firstname": "ale",
  "lastname": "laneri",
  "email": "bla@gmail",
  "password": "test12345",
  "username": "magno"
}

###

POST http://localhost:8083/api/v1/session/703834b3-160c-42d8-a9a9-1aef25211b62
Content-Type: application/json

{
  "id": "55ffe178-c544-4a17-9b7b-6f87cff9754c",
  "firstname": "tomas",
  "lastname": "pransky",
  "email": "bgbgbgbgb@gmail",
  "password": "1111122222222bbbbbb",
  "username": "shokomuus"
}

###

GET http://localhost:8083/account/alejandro.r.laneri@gmail.com

###
POST http://localhost:8083/api/v1/searchSession3
Content-Type: application/json

{
  "id": 1,
  "firstname": "Alejandro",
  "lastname": "Laneri",
  "email": "alejandro.r.laneri@gmail.com",
  "password": "$2a$10$.WNat6KjIoO4O.OL0gUBROw7l7hJ8YuiPMkhw2diSXwlIvYDPo4ZC",
  "username": null
}

###

GET http://localhost:8083/api/v1/sessions